// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/objects/objectiface/iface.go

// Package mock_objectiface is a generated GoMock package.
package mock_objectiface

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockObjecter is a mock of Objecter interface
type MockObjecter struct {
	ctrl     *gomock.Controller
	recorder *MockObjecterMockRecorder
}

// MockObjecterMockRecorder is the mock recorder for MockObjecter
type MockObjecterMockRecorder struct {
	mock *MockObjecter
}

// NewMockObjecter creates a new mock instance
func NewMockObjecter(ctrl *gomock.Controller) *MockObjecter {
	mock := &MockObjecter{ctrl: ctrl}
	mock.recorder = &MockObjecterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockObjecter) EXPECT() *MockObjecterMockRecorder {
	return m.recorder
}

// ID mocks base method
func (m *MockObjecter) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID
func (mr *MockObjecterMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockObjecter)(nil).ID))
}
