// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/environment/environmentiface/iface.go

// Package mock_environmentiface is a generated GoMock package.
package mock_environmentiface

import (
	gomock "github.com/golang/mock/gomock"
	coordinate "github.com/jecolasurdo/marsrover/pkg/coordinate"
	objectiface "github.com/jecolasurdo/marsrover/pkg/object/objectiface"
	reflect "reflect"
)

// MockEnvironmenter is a mock of Environmenter interface
type MockEnvironmenter struct {
	ctrl     *gomock.Controller
	recorder *MockEnvironmenterMockRecorder
}

// MockEnvironmenterMockRecorder is the mock recorder for MockEnvironmenter
type MockEnvironmenterMockRecorder struct {
	mock *MockEnvironmenter
}

// NewMockEnvironmenter creates a new mock instance
func NewMockEnvironmenter(ctrl *gomock.Controller) *MockEnvironmenter {
	mock := &MockEnvironmenter{ctrl: ctrl}
	mock.recorder = &MockEnvironmenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEnvironmenter) EXPECT() *MockEnvironmenterMockRecorder {
	return m.recorder
}

// GetDimensions mocks base method
func (m *MockEnvironmenter) GetDimensions() coordinate.Point {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDimensions")
	ret0, _ := ret[0].(coordinate.Point)
	return ret0
}

// GetDimensions indicates an expected call of GetDimensions
func (mr *MockEnvironmenterMockRecorder) GetDimensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDimensions", reflect.TypeOf((*MockEnvironmenter)(nil).GetDimensions))
}

// PlaceObject mocks base method
func (m *MockEnvironmenter) PlaceObject(arg0 objectiface.Objecter, arg1 coordinate.Point) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceObject", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PlaceObject indicates an expected call of PlaceObject
func (mr *MockEnvironmenterMockRecorder) PlaceObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceObject", reflect.TypeOf((*MockEnvironmenter)(nil).PlaceObject), arg0, arg1)
}

// MoveObject mocks base method
func (m *MockEnvironmenter) MoveObject(arg0 objectiface.Objecter, arg1 coordinate.Point) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveObject", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveObject indicates an expected call of MoveObject
func (mr *MockEnvironmenterMockRecorder) MoveObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveObject", reflect.TypeOf((*MockEnvironmenter)(nil).MoveObject), arg0, arg1)
}

// ShowObjects mocks base method
func (m *MockEnvironmenter) ShowObjects() map[coordinate.Point][]objectiface.Objecter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowObjects")
	ret0, _ := ret[0].(map[coordinate.Point][]objectiface.Objecter)
	return ret0
}

// ShowObjects indicates an expected call of ShowObjects
func (mr *MockEnvironmenterMockRecorder) ShowObjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowObjects", reflect.TypeOf((*MockEnvironmenter)(nil).ShowObjects))
}
